general:
  parameters:
    SubnetId: "subnet-040207590a7c81393"
    SecurityGroup: "sg-03d8a2c81db1a4dc8"
    LocalVMName: awesomerobot1
    AdminPassword: QWbGk1VhWiN8m
    UiRobotType: Unattended
    RobotRole: localadmin
    UiRobotName: awesome.robot
    UiRobotPassword: QWbGk1VhWiN8m
    OrchestratorURL: https://corp-orchestrator.com/
    OrchestratorAPIUser: apiuser
    OrchestratorAPIPassword: QWbGk1VhWiN8m
    OrchestratorTenant: Default
    Domain: corp.com
    SubDomain: app
    HAAUser: admin@corp.com
    HAAPassword: QWbGk1VhWiN8m
    RDSUsername: corpaws
    RDSPassword: QWbGk1VhWiN8m
    OrchestratorPassPhrase: QWbGk1VhWiN8m
    OrchestratorPassword: QWbGk1VhWiN8m
    OrchestratorLicense: ""
    HAALicense: ""
project:
  name: quickstart-uipath-orchestrator
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ap-east-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - me-south-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  shorten_stack_name: true
  #s3_bucket: tcat-quickstart-uipath-orchestratorlnc7yiwd
tests:
  default:
    template: ./templates/orchestrator/master.template.json # ./templates/robot/master.template.json
    regions:
    - us-east-1
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      KeyPairName: sshvans
      StorageBucket: "uip$[taskcat_autobucket]"
      GatewayName: "uipathgateway"
      QSS3KeyPrefix: "quickstart-uipath-orchestrator/"
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: $[taskcat_current_region]
      Domain: uipathqs.t.quickstart.awspartner.com