general:
  parameters:
    SubnetId: "subnet-040207590a7c81393"
    SecurityGroup: "sg-03d8a2c81db1a4dc8"
    LocalVMName: awesomerobot1
    AdminPassword: QWbGk1VhWiN8m
    UiRobotType: Unattended
    RobotRole: localadmin
    UiRobotName: awesome.robot
    UiRobotPassword: QWbGk1VhWiN8m
    OrchestratorURL: https://corp-orchestrator.com/
    OrchestratorAPIUser: apiuser
    OrchestratorAPIPassword: QWbGk1VhWiN8m
    OrchestratorTenant: Default
    Domain: corp.com
    SubDomain: app
    HAAUser: admin@corp.com
    HAAPassword: QWbGk1VhWiN8m
    RDSUsername: corpaws
    RDSPassword: QWbGk1VhWiN8m
    OrchestratorPassPhrase: QWbGk1VhWiN8m
    OrchestratorPassword: QWbGk1VhWiN8m
    OrchestratorLicense: ""
    HAALicense: ""
project:
  name: uipath
  regions:
    - us-east-1
  shorten_stack_name: true
tests:
  default:
    template: ./templates/orchestrator/master.template.json # ./templates/robot/master.template.json
    regions:
    - us-east-1
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      KeyPairName: existing_key
      StorageBucket: "uip$[taskcat_autobucket]"
      GatewayName: "uipathgateway"
      QSS3KeyPrefix: "uip/"
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: us-east-1